"""Initial migration.

Revision ID: 9848dfd5f2ba
Revises: 
Create Date: 2024-07-25 16:10:29.854375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9848dfd5f2ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_user', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=65),
               type_=sa.String(length=65),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('sub',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['nome'])
        batch_op.create_unique_constraint(None, ['sub'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('sub',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=65),
               type_=mysql.VARCHAR(length=65),
               nullable=True)

    # ### end Alembic commands ###
